version: '3.9'
services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tool_keeper_ai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tool_keeper_ai_db;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    command: ["sh", "-c", "dotnet tool install --global dotnet-ef && dotnet ef database update && dotnet ToolKeeperAIBackend.dll"]

volumes:
  pgdata: